name: Tests

on:
  push:
    branches: [master, tf-migration]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: test

      - name: Run unit tests
        run: pixi run -e test test
